apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: diogopereiraezo/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: localhost #only workds inside the same pod
              value: "10.102.118.89"